# Generated by Django 3.2.16 on 2023-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file_name', models.CharField(max_length=100, verbose_name='配置文件名称')),
                ('config_file_path', models.CharField(max_length=1024, verbose_name='配置文件路径')),
            ],
            options={
                'db_table': 'testcase_configfile',
            },
        ),
    ]
