# Generated by Django 3.2.16 on 2023-09-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseConfigTemplateFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=100, verbose_name='格式名称')),
                ('format_sheet', models.CharField(max_length=1024, verbose_name='格式对应的控件')),
            ],
            options={
                'db_table': 'testcase_template_format',
            },
        ),
        migrations.CreateModel(
            name='TestCaseConfigTemplateWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=100, verbose_name='控件名字')),
                ('widget_file', models.CharField(max_length=1024, verbose_name='控件对应的文档')),
            ],
            options={
                'db_table': 'testcase_tempalte_widget',
            },
        ),
        migrations.AddField(
            model_name='testcaseconfigmodel',
            name='batch_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
