# Generated by Django 3.2.16 on 2023-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_auto_20230906_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseconfigtemplateformat',
            name='format_sheet',
            field=models.CharField(max_length=1024, null=True, verbose_name='格式对应的控件'),
        ),
        migrations.AlterField(
            model_name='testcaseconfigtemplatewidget',
            name='widget_file',
            field=models.CharField(max_length=1024, null=True, verbose_name='控件对应的文档'),
        ),
    ]
