# Generated by Django 3.2.16 on 2023-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_auto_20230906_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseconfigmodel',
            name='config_file_type',
            field=models.CharField(default='6', max_length=100, verbose_name='配置文件类型'),
        ),
    ]
