# Generated by Django 3.2.16 on 2023-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_testcaseconfigmodel_config_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseconfigmodel',
            name='tags',
            field=models.DateTimeField(null=True, verbose_name='文件标识'),
        ),
        migrations.AlterField(
            model_name='testcaseconfigmodel',
            name='config_file_type',
            field=models.CharField(max_length=100, null=True, verbose_name='配置文件类型'),
        ),
    ]
