# Generated by Django 3.2.16 on 2023-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_auto_20230911_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseconfigmodel',
            name='tags',
            field=models.CharField(max_length=32, null=True, verbose_name='文件标识'),
        ),
    ]
