# Generated by Django 3.2.16 on 2023-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_testcaseconfigmodel_data_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脚本测试套件名字')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父id')),
                ('level', models.IntegerField(default=0, verbose_name='文件级别')),
                ('path', models.CharField(default=0, max_length=1024, verbose_name='文件路径')),
            ],
            options={
                'db_table': 'testcase_script_config',
            },
        ),
    ]
