# Generated by Django 3.2.16 on 2023-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_auto_20230921_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptconfig',
            name='tags',
            field=models.CharField(max_length=32, null=True, verbose_name='文件标识'),
        ),
    ]
