# Generated by Django 3.2.16 on 2023-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_scriptconfig_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptconfig',
            name='tags',
            field=models.CharField(default=0, max_length=32, null=True, verbose_name='文件标识'),
        ),
    ]
