# Generated by Django 3.2.16 on 2023-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0011_alter_scriptconfig_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptconfig',
            name='type',
            field=models.CharField(default=0, max_length=32, null=True, verbose_name='文件类型'),
        ),
    ]
