# Generated by Django 3.2.16 on 2024-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0013_auto_20231020_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='RanScriptResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_path', models.TextField(null=True, verbose_name='脚本路径')),
                ('test_name', models.CharField(max_length=128, null=True, verbose_name='用例名字')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='用例执行状态')),
                ('data_uuid', models.CharField(max_length=128, null=True, verbose_name='数据执行批次')),
                ('user_id', models.IntegerField(null=True, verbose_name='用户id')),
                ('batch_time', models.DateTimeField(null=True, verbose_name='批次时间')),
            ],
            options={
                'db_table': 'testcase_ran_script_result',
            },
        ),
    ]
