# Generated by Django 3.2.16 on 2024-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0015_alter_scriptconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageToolDataFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_conten_id', models.IntegerField(null=True, verbose_name='数据结构表id')),
                ('file_type', models.CharField(max_length=32, null=True, verbose_name='文件类型')),
                ('file_path', models.TextField(null=True, verbose_name='文件路径')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'managetool_data_file',
            },
        ),
    ]
