# Generated by Django 3.2.16 on 2024-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningProcessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=128, verbose_name='批次id')),
                ('data_id', models.CharField(max_length=128, null=True, verbose_name='数据批次id')),
                ('url_all', models.TextField(null=True, verbose_name='baseline_url')),
                ('param_all', models.TextField(null=True, verbose_name='baseline_参数')),
                ('identify', models.CharField(max_length=64, null=True, verbose_name='标识-baseline/exp')),
            ],
            options={
                'verbose_name': '执行过程记录表',
                'verbose_name_plural': '执行过程记录表',
                'db_table': 'running_process_data_table',
            },
        ),
    ]
