# Generated by Django 3.2.16 on 2024-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=128, verbose_name='系统名称')),
                ('leve_1_name', models.CharField(max_length=128, verbose_name='一级目录')),
                ('leve_2_name', models.CharField(max_length=128, verbose_name='二级目录')),
                ('leve_3_name', models.CharField(max_length=128, verbose_name='三级目录')),
                ('leve_4_name', models.CharField(max_length=128, verbose_name='四级目录')),
                ('importance_level', models.CharField(max_length=128, verbose_name='重要级别')),
                ('function_name', models.CharField(max_length=128, verbose_name='功能名称')),
                ('function_code', models.CharField(max_length=128, verbose_name='功能编号')),
            ],
        ),
    ]
