# Generated by Django 3.2.16 on 2024-06-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_systemcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcontent',
            options={'verbose_name': '系统结构表', 'verbose_name_plural': '系统结构表'},
        ),
        migrations.AlterModelTable(
            name='systemcontent',
            table='system_content_table',
        ),
    ]
