# Generated by Django 3.2.16 on 2024-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_auto_20240607_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcontent',
            name='function_code',
            field=models.CharField(max_length=128, null=True, verbose_name='功能编号'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='importance_level',
            field=models.CharField(max_length=128, null=True, verbose_name='重要级别'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='leve_1_name',
            field=models.CharField(max_length=128, null=True, verbose_name='一级目录'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='leve_2_name',
            field=models.CharField(max_length=128, null=True, verbose_name='二级目录'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='leve_3_name',
            field=models.CharField(max_length=128, null=True, verbose_name='三级目录'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='leve_4_name',
            field=models.CharField(max_length=128, null=True, verbose_name='四级目录'),
        ),
        migrations.AlterField(
            model_name='systemcontent',
            name='system_name',
            field=models.CharField(max_length=128, null=True, verbose_name='系统名称'),
        ),
    ]
