# Generated by Django 3.2.16 on 2024-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_auto_20240608_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=128, null=True, verbose_name='文件类型')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件类型表',
                'verbose_name_plural': '文件类型表',
                'db_table': 'file_type_table',
            },
        ),
        migrations.AddField(
            model_name='systemcontent',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
    ]
