name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:  # 支持手动触发

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller your_script.py --onefile

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe-output
        path: dist/your_script.exe
